### ISSUE TITLE
Crash with <ol> or <ul> (PARAGRAPH span must end at paragraph boundary)

### ISSUE THREAD

**Issue by BlueMango92** [SufficientlySecure/html-textview#58]
My app crashes if I set an Html String containing `<ol>` or `<ul>` tags. 

This String causes a crash: 
`<ul><li>Test</li></ul><div>Hello</div>`

My logcat says: 
`FATAL EXCEPTION: main
Process: com.bluemango.keynote, PID: 14353
java.lang.RuntimeException: PARAGRAPH span must end at paragraph boundary (6 follows  )
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:95)
at android.text.SpannableStringInternal.<init>(SpannableStringInternal.java:52)
at android.text.SpannedString.<init>(SpannedString.java:30)`

UPDATE:
I notice that it crashes only if I set `android:singleLine="true"`

**Comment by dschuermann** [comment]
Please try again with 3.0 and report back
