### ISSUE TITLE
EmptyStackException on "<li>text</li>"

### ISSUE THREAD

**Issue by ashishpatil396** [SufficientlySecure/html-textview#86]
I was set Text Read from Assets and set Html Page then i got error EmptyStackException 

  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                   Caused by: java.util.EmptyStackException
                                                                      at java.util.Stack.peek(Stack.java:57)
                                                                      at org.sufficientlysecure.htmltextview.HtmlTagHandler.handleTag(HtmlTagHandler.java:155)
                                                                      at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:522)
                                                                      at android.text.HtmlToSpannedConverter.startElement(Html.java:761)
                                                                      at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
                                                                      at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
                                                                      at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1016)
                                                                      at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:566)
                                                                      at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
                                                                      at android.text.HtmlToSpannedConverter.convert(Html.java:442)
                                                                      at android.text.Html.fromHtml(Html.java:136)
                                                                      at org.sufficientlysecure.htmltextview.HtmlTextView.setHtml(HtmlTextView.java:101)
                                                                      at com.app.montessori.activities.TermsNConditionActivity.onCreate(TermsNConditionActivity.java:57)
                                                                      at android.app.Activity.performCreate(Activity.java:5990)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jeffbordon** [comment]
I'm getting the same error, seem that it is caused by `HtmlTagHandler`

**Comment by jeffbordon** [comment]
I was able to reproduce the Exception with following code:
`mTextViewDescr.setHtml("<li>some text</li>");`

Following code works
`mTextViewDescr.setHtml("<ul><li>some text</li></ul>");`

However, would be great to catch this exception somewhere in `HtmlTagHanlder`

**Comment by dschuermann** [comment]
I am open for pull requests to fix this.
