### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by kwong93** [SufficientlySecure/html-textview#95]
I am getting ActivityNotFoundException when clicking an invalid link, for example, a link to a subreddit for reddit:

`<a href="/all">all</a>
`

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=/r/all (has extras) }
                                                                          at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
                                                                          at android.app.Instrumentation.execStartActivity(Instrumentation.java:1499)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3942)
                                                                          at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3889)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                          at android.app.Activity.startActivity(Activity.java:4213)
                                                                          at android.app.Activity.startActivity(Activity.java:4181)
                                                                          at android.text.style.URLSpan.onClick(URLSpan.java:62)
                                                                          at org.sufficientlysecure.htmltextview.LocalLinkMovementMethod.onTouchEvent(LocalLinkMovementMethod.java:64)
                                                                          at android.widget.TextView.onTouchEvent(TextView.java:9600)
                                                                          at org.sufficientlysecure.htmltextview.HtmlTextView.onTouchEvent(HtmlTextView.java:154)
                                                                          at android.view.View.dispatchTouchEvent(View.java:8981)
```

This causes a crash for Android L 5.1 on my Samsung Galaxy S4, however with my Nexus 5X 7.1.1 it does not crash, and does nothing when clicking on the link as expected.

**Comment by aminecmi** [comment]
I'm having the same issue.
The issue seams to be that relative urls aren't transformed to absolute ones.
